### ISSUE TITLE
Multi vhosts

### ISSUE THREAD

**Issue by dkouvdis** [ymainier/vagrant-lamp#10]
Hi.

Sorry for contacting you here, does this repo supports multi vhosts?
Creating like this local.dev project.dev project2.dev

If yes, I am weak with Linux and chef configuration. How would I do it, I did not really catch the documentation.

Thanks
ps: I have tried to use your repo but with no success.

**Comment by ymainier** [comment]
Sorry, this is not the target of this repo :-)

Have a look here to customize the mysql cookbook to your need : https://github.com/opscode-cookbooks/apache2#apache_site
