### ISSUE TITLE
vagrant init results in errors

### ISSUE THREAD

**Issue by paulschwarz** [ymainier/vagrant-lamp#2]
Having followed the instructions in the README I get the following errors.

$ vagrant init
uname: invalid option -- o
Try `uname --help' for more information.
/c/vagrant/vagrant/bin/vagrant: line 34: [: =: unary operator expected
c:/vagrant/vagrant/embedded/lib/ruby/gems/1.9.1/gems/vagrant-1.0.3/lib/vagrant/config/vm.rb:44:in`to_s': wrong number of arguments(1 for 0) (ArgumentError)
        from c:/vagrant/vagrant/embedded/lib/ruby/gems/1.9.1/gems/vagrant-1.0.3/lib/vagrant/config/vm.rb:44:in `forward_port'
        from c:/Users/Paul/Eclipse/Workspaces/PHP/Joomla Projects/Active Escapes/Vagrantfile:19:in`block in <top (required)>'
        from c:/vagrant/vagrant/embedded/lib/ruby/gems/1.9.1/gems/vagrant-1.0.3/lib/vagrant/config/loader.rb:83:in `call'
        from c:/vagrant/vagrant/embedded/lib/ruby/gems/1.9.1/gems/vagrant-1.0.3/lib/vagrant/config/loader.rb:83:in`block (2 levels) in load'
        from c:/vagrant/vagrant/embedded/lib/ruby/gems/1.9.1/gems/vagrant-1.0.3/lib/vagrant/config/loader.rb:79:in `each'
        from c:/vagrant/vagrant/embedded/lib/ruby/gems/1.9.1/gems/vagrant-1.0.3/lib/vagrant/config/loader.rb:79:in`block in load'
        from c:/vagrant/vagrant/embedded/lib/ruby/gems/1.9.1/gems/vagrant-1.0.3/lib/vagrant/config/loader.rb:76:in `each'
        from c:/vagrant/vagrant/embedded/lib/ruby/gems/1.9.1/gems/vagrant-1.0.3/lib/vagrant/config/loader.rb:76:in`load'
        from c:/vagrant/vagrant/embedded/lib/ruby/gems/1.9.1/gems/vagrant-1.0.3/lib/vagrant/environment.rb:387:in `block in load_config!'
        from c:/vagrant/vagrant/embedded/lib/ruby/gems/1.9.1/gems/vagrant-1.0.3/lib/vagrant/environment.rb:392:in`call'
        from c:/vagrant/vagrant/embedded/lib/ruby/gems/1.9.1/gems/vagrant-1.0.3/lib/vagrant/environment.rb:392:in `load_config!'
        from c:/vagrant/vagrant/embedded/lib/ruby/gems/1.9.1/gems/vagrant-1.0.3/lib/vagrant/environment.rb:327:in`load!'
        from c:/vagrant/vagrant/embedded/lib/ruby/gems/1.9.1/gems/vagrant-1.0.3/bin/vagrant:40:in `<top (required)>'
        from c:/vagrant/vagrant/bin/../embedded/bin/vagrant:19:in`load'
        from c:/vagrant/vagrant/bin/../embedded/bin/vagrant:19:in `<main>'

**Comment by ymainier** [comment]
Hi paul,

Have you tried to use vagrant without vagrant-lamp ? Have you the same problem ?
If you haven't try it, could you follow these instructions http://vagrantup.com/docs/getting-started/index.html and see what is going on ?

Y.

**Comment by paulschwarz** [comment]
If I follow the basic instructions from the vagrantup.com site It seems to just work. My cmd looks like this right now:

C:\Users\Paul\Test>vagrant up
[default] Importing base box 'lucid32'...
[default] Matching MAC address for NAT networking...
[default] Clearing any previously set forwarded ports...
[default] Forwarding ports...
[default] -- 22 => 2222 (adapter 1)
[default] Creating shared folders metadata...
[default] Clearing any previously set network interfaces...
[default] Booting VM...
[default] Waiting for VM to boot. This can take a few minutes.

**Comment by ymainier** [comment]
Ok, so you are able to boot vagrant !

Could you try to copy all files and folder of vagrant-lamp (most importantly the `Vagrantfile` file and the `cookbooks` directory) in the directory where you successfully launch `vagrant up`

**Comment by paulschwarz** [comment]
I created a Test directory and ran vagrant init and vagrant up and it worked, I get the lucid32 login screen.
The I manually copied your files from Git and pasted them into Test.
I then ran vagrant up and I get the exact same output as per my first comment in this thread.

**Comment by ymainier** [comment]
Paul,

I find and correct a bug, but I'm not sure that it will help with your problem.
Could you pull the last version from github and give it a try : please use a fresh directory, to ensure that there is no side effect from your previous test.

What I corrected : Wrong number of argument in config.vm.forward_port.
Why it might not correct your problem : the error message I had was different from yours, but I have ruby 1.8.7 (you seem to have 1.9.1).

So tell me if it helps :)

**Comment by paulschwarz** [comment]
Fixed, well done.
