### ISSUE TITLE
Error during provisioning

### ISSUE THREAD

**Issue by paulschwarz** [ymainier/vagrant-lamp#3]
I am running Ruby 1.9.3p125 on Windows 7 via the CMD shell. This is the provisioning output:

[default] Running chef-solo...
stdin: is not a tty
[Mon, 21 May 2012 15:28:48 +0200] INFO: **\* Chef 0.10.8 ***
[Mon, 21 May 2012 15:28:48 +0200] INFO: Setting the run_list to ["recipe[vagrant_main]"] from JSON
[Mon, 21 May 2012 15:28:48 +0200] INFO: Run List is [recipe[vagrant_main]]
[Mon, 21 May 2012 15:28:48 +0200] INFO: Run List expands to [vagrant_main]
[Mon, 21 May 2012 15:28:48 +0200] INFO: Starting Chef Run for lucid32
[Mon, 21 May 2012 15:28:48 +0200] INFO: Running start handlers
[Mon, 21 May 2012 15:28:48 +0200] INFO: Start handlers complete.
[Mon, 21 May 2012 15:28:48 +0200] WARN: Missing gem 'mysql'
[Mon, 21 May 2012 15:28:49 +0200] INFO: Processing execute[apt-get update] action run (apt::default line 20)
[Mon, 21 May 2012 15:28:49 +0200] INFO: execute[apt-get update] sh(apt-get update)
[Mon, 21 May 2012 15:36:08 +0200] INFO: execute[apt-get update] ran successfully
[Mon, 21 May 2012 15:36:09 +0200] INFO: Processing package[mysql-devel] action install (mysql::client line 20)
[Mon, 21 May 2012 15:39:00 +0200] INFO: package[mysql-devel] installed version 5.1.62-0ubuntu0.10.04.1
[Mon, 21 May 2012 15:39:00 +0200] INFO: Processing package[mysql-client] action install (mysql::client line 43)
[Mon, 21 May 2012 15:44:14 +0200] INFO: package[mysql-client] installed version 5.1.62-0ubuntu0.10.04.1
[Mon, 21 May 2012 15:44:14 +0200] INFO: Processing gem_package[mysql] action install (mysql::client line 60)
[Mon, 21 May 2012 15:44:35 +0200] ERROR: gem_package[mysql](mysql::client line 60) has had an error
[Mon, 21 May 2012 15:44:35 +0200] ERROR: Running exception handlers
[Mon, 21 May 2012 15:44:35 +0200] ERROR: Exception handlers complete
[Mon, 21 May 2012 15:44:35 +0200] FATAL: Stacktrace dumped to /tmp/vagrant-chef-1/chef-stacktrace.out
[Mon, 21 May 2012 15:44:35 +0200] FATAL: Gem::Installer::ExtensionBuildError: gem_package[mysql](mysql::client line 60) had an error: Gem::Installer::Extension
BuildError: ERROR: Failed to build gem native extension.

```
    /opt/vagrant_ruby/bin/ruby extconf.rb
```

checking for mysql_ssl_set()... yes
checking for rb_str_set_len()... yes
checking for rb_thread_start_timer()... yes
checking for mysql.h... yes
creating Makefile

make
sh: make: not found

Gem files will remain installed in /opt/vagrant_ruby/lib/ruby/gems/1.8/gems/mysql-2.8.1 for inspection.
Results logged to /opt/vagrant_ruby/lib/ruby/gems/1.8/gems/mysql-2.8.1/ext/mysql_api/gem_make.out
Chef never successfully completed! Any errors should be visible in the
output above. Please fix your recipes so that they properly complete.

**Comment by ciastek** [comment]
`$ sudo apt-get install build-essential`

**Comment by paulschwarz** [comment]
However, the point of chef is to provision automatically, therefore I would want to add this to a recipe. My guess would be somewhere in here: https://github.com/ymainier/vagrant-lamp/blob/master/cookbooks/apt/recipes/default.rb
