### ISSUE TITLE
MySQL root password error

### ISSUE THREAD

**Issue by 0x73706f6f6b** [ymainier/vagrant-lamp#7]
Should we instruct users to set a password for mysql's root since phpmyadmin keeps warning me about the default password being set to root. If so then:

**Log in to Vagrant**
`$ vagrant ssh`  

**Log in to MySQL**
`$ mysql -uroot -p`
`Enter password: root` (__The default 'root' password is root__)

**MySQL command to set password for root**
`mysql> SET PASSWORD FOR root@localhost = PASSWORD('new password');`

**Comment by ymainier** [comment]
Hi @dkabistan 

Could you tell me where you see this warning ?

**Comment by 0x73706f6f6b** [comment]
@ymainier After the setup, phpMyAdmin complains about the password being root. I know it's minimal, just letting you know.

**Comment by ymainier** [comment]
Cannot reproduce
